### PR TITLE
Fix couple misused characters in zh-TW

### PR DESCRIPTION
**Pull request by amazingandyyy**
### What does it do?

Fix typos and some misused characters

### Any helpful background information?

- The first version of translation has many simplified Chinese characters, this is due to many online translators/translating engine nowadays having difficulty to use decent "transitional Chinese"
- I am native Taiwanese who can correct them

### Any new dependencies? Why were they added?

ignore `.idea` file, IntelliJ is a popular editors and we should ignore `.idea`(the IntelliJ confirmation file) if possible

### Does it close any issues?

No issue

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Thanks @amazingandyyy!

**Comment by kavimaluskam** [comment]
Thanks @amazingandyyy would you mind to update the ZH-HK file as well? 

I think it make sense to in sync both traditional files.

**Comment by with-heart** [comment]
I think that makes sense @kavimaluskam! Would be great to tackle both.

**Comment by amazingandyyy** [comment]
Altho they are both traditional Chinese, but in reality, HK use different terms and characters than TW's

As a Taiwanese, I suggest having members from HK to translate for zh-HK for respect HK's community

**Comment by amazingandyyy** [comment]
I think we can merge this first and for put zh-HK correction on another PR if anyone is capable with it.

**Comment by with-heart** [comment]
@amazingandyyy That's fair! We'll let an HK'er translate `zh-HK`.

@allcontributors please add @amazingandyyy for translation

**Pull request merged**
