### PR TITLE
Reset the repo and remove unwanted stuff

### PR DESCRIPTION
**Pull request by Nazeeh21**
Removed the minting functionality and tests that we are no longer using it.

### CODE REVIEW

**Comment by Nazeeh21** [comment]
@with-heart I have removed the unwanted stuff and tried resetting the repo. LMK if I have missed something or needs to be changed.

**Review by with-heart — CHANGES_REQUESTED** [review]
All of the changes are great except for `src/pages/index.tsx`. Do we want to remove the content from that page? It'd leave `developerdao.com` basically empty

**Comment by Nazeeh21** [comment]
Yup, it'll leave the website blank. I thought that it'll help to make a fresh start, but yeah definitely not at the cost of an empty website.

**Comment by Nazeeh21** [comment]
@with-heart Pls do let me know if more changes are required?

**Comment by with-heart** [comment]
I think we're good to go! Thanks a lot for cleaning things up @Nazeeh21!

**Pull request merged**
