### PR TITLE
Add the Values section

### LINKED ISSUE #210: Implement Values Section

### PR DESCRIPTION
**Pull request by sam0110**
### What does it do?

Adds the Values component. It contains the DAO's values, mission and goals. It also contains a link to the wiki.

### Any helpful background information?

[Discord discussion](https://discord.com/channels/883478451850473483/884852584941232169/946494436429430824)

### Any new dependencies? Why were they added?

No

### Relevant screenshots/gifs

image

image

### Does it close any issues?

Closes #210

### CODE REVIEW

**Comment by sam0110** [comment]
The wiki link doesn't quite match the Figma design yet. I'll fix that.

**Comment by sam0110** [comment]
@Nazeeh21 This is ready for review!

**Review by Nazeeh21 — CHANGES_REQUESTED** [review]
Overall it is great. Just a few changes are required that are mentioned below:
- There should be more gap between **Mission**, **Goals** and **Wiki** section for the mobile devices
- Fontsize for the **Values** is `3.375rem` for mobile devices as well, it should be `30px` for the mobile and vice-versa for the other texts in the **Values ** section (Please recheck the size for the texts for both mobile and desktop versions)
- **Mission** and **Values** section's white borders are not aligned properly (not centered horizontally), adding `margin-left` to the div and revising its width might fix it.

https://user-images.githubusercontent.com/56908732/157424805-836df871-ed4b-459d-90fd-1431b175ddcc.mov

**Comment by Nazeeh21** [comment]
hey @sam0110, just let me know if you are stuck somewhere or wants help

**Comment by sam0110** [comment]
@Nazeeh21 Sorry for the delay. This is once again ready for review.

**Comment by Nazeeh21** [comment]
Sure @sam0110, will review it soon.

**Comment by Nazeeh21** [comment]
@with-heart Can you authorize vercel to deploy this?

**Comment by Nazeeh21** [comment]
Great work @sam0110, will merge it once will get the vercel authorization from @with-heart.

@with-heart Can you please authorize vercel deployment for this PR ? also would love to hear your thoughts on this PR

**Review by Nazeeh21 — APPROVED** [review]

**Comment by sam0110** [comment]
It looks like that deploy is not the latest version.

**Comment by Nazeeh21** [comment]
> It looks like that deploy is not the latest version.

Why do you feel like that?

**Comment by Nazeeh21** [comment]
though we have deployed to vercel, don't why it is still failing

**Comment by sam0110** [comment]
> Why do you feel like that?

The spacing, font sizes and responsiveness compared to my version. It deployed the first version you reviewed instead of the most recent one.

**Comment by Nazeeh21** [comment]
Ohh, let me check locally that.

**Comment by Nazeeh21** [comment]
image
I tested out this locally and the component seems alright but the font sizes of components above and below that got reduced. lol. Don't worry I'll take care of that while merging it.

**Comment by Nazeeh21** [comment]
@sam0110 I tried fixing the font sizes for the Header and Footer, but it got more messed up as `theme.ts` got modified on your PR. 

image

This is what I ended with. 
I'm merging the `staging` branch with your branch so that PR contains all the latest commits and stays updated.
Tasks to be done are fixing the margin and font sizes of the margin section. 
Try not to modify the existing font sizes of `Link`, `Text` and `Heading` in `theme.ts` as it will disturb sizes for other elements as well.

Lmk or tag me on Discord if you need more help

**Comment by sam0110** [comment]
@Nazeeh21 Thanks for taking another look at this! 

About the changes in `theme.ts`. I wrapped all of the variants in [this `components` object](https://github.com/Developer-DAO/developerdao.com/pull/212/commits/cf6a1617fd7dbadb1b6643ae2a20bca2c7bfc8fa#diff-0e21fb1c9519a397050defc2148a2d1b966a0982cc4cf196e1e6b007f8d095e5R26) which was missing. They were not being registered before so they had no effect. The other text changed as well because the variants that previously had no effect started working. For example, I can see that the "Developer DAO" text next to the logo in both the `Header` and `Footer` components use `variant="medium"`. In this case it should be removed or switched to a matching variant. I am happy to do this! :slightly_smiling_face: I think it is important that we use the variants as much as we can to keep a consistent style.

I did not modify existing variants except for `Link` but that one is not formatted correctly and is not being used at all. I will remove that change.

I am thinking this:
- I take my commits and rebase them on `staging` to update my branch and keep a clean commit history
- Remove the `Link` variant that isn't doing anything
- Create an issue to fix the font sizes which I will complete ASAP! 

Does this sound good to you? :smile:

**Comment by sam0110** [comment]
I should have made a PR to fix the variants immediately. :thinking: So I will definitely handle with the problems it caused!

**Comment by Nazeeh21** [comment]
@sam0110 I completely agree with you. I'm rebasing your branch with the `staging` branch.
Regarding the missing variants, I removed them to maintain the font sizes. If you can take care of the font sizes of all the other components, I'll revert back the changes I made in `theme.ts`.

Also, I'm creating a new issue and assigning it to you. You can make the changes in this existing PR only and we can merge it once its ready.

**Comment by sam0110** [comment]
For background: We clarified the config issue with the variants in Discord. We will merge this and then I will fix the affected components in #218

@Nazeeh21 This can be merged now. I have the changes ready for #218 ready too.

**Pull request merged**
