### PR TITLE
Header component

### PR DESCRIPTION
**Pull request by kkeaveney**
### **What does it do?**

Adds new Header component with initial layout, sizes, padding and margin. These props may need adjusting once the other components are merged.

**Any helpful background information?**
[Discord Chat](https://discord.com/channels/883478451850473483/884852584941232169/946474631760601098)

### **Any new dependencies? *
No

Relevant screenshots

Desktop
Mobile_close
Mobile_menu

### Does it close any issues?
Draft PR #207

### CODE REVIEW

**Comment by Nazeeh21** [comment]
@kkeaveney below screenshot is of 1440px size and its not synchronizing with the design, might need to decrease the gap between the nav items based on different breakpoints

image

**Comment by Nazeeh21** [comment]
@kkeaveney LMK if I can help in any way

**Comment by andyrobert3** [comment]
image
image
image
image
image

@Nazeeh21 please take a look, responsive on multiple screen sizes, tested on chrome

**Comment by Nazeeh21** [comment]
@andyrobert3 PR looks amazing. I think it is ready to merge

**Comment by andyrobert3** [comment]
When will this be merged @Nazeeh21 ?

**Comment by Nazeeh21** [comment]
I'm waiting for the vercel deployment authorization. Also, I am at Ethdubai, so I am not able to make much time for it. But I'll make sure to get it merged by this weekend. Sorry for the delay.

**Pull request merged**
