### PR TITLE
Updated chinese family translation

### PR DESCRIPTION
**Pull request by kavimaluskam**
Sorry for (myself) missing the updates recently, so busy with a new position in berlin orz

### What does it do?
- Update chinese family translation with missing keys
- Using `$t(title)` translation
- I updated some naming (e.g. `name` -> `開發者DAO`) due to the growthing complexity in wordings... please amend or discuss with you are feeling weird on the chinese wordings!

### Relevant screenshots/gifs

`zh` - Language Settings: `Chinese` or  `zh-cn` - Language Settings: `Chinese (Simplified)`:
Screenshot 2021-09-28 at 8 37 24 PM
Screenshot 2021-09-28 at 8 37 30 PM

`zh-hk` - Language Settings:`Chinese (Hong Kong)` or `zh-tw` - Language Settings: `Chinese (Traditional)`
Screenshot 2021-09-28 at 8 38 14 PM
Screenshot 2021-09-28 at 8 38 08 PM

### Does it close any issues?

Relating to issues: #88, #95, #118

### CODE REVIEW

**Comment by kavimaluskam** [comment]
Meanwhile, I found that the top menu (`Home`, `Projects`) are missing translations in all languages. 
Shall I open in issue for that 🤔 .

**Comment by kavimaluskam** [comment]
Sorry just checked PR: https://github.com/Developer-DAO/developer-dao/pull/117

Shall update this PR after https://github.com/Developer-DAO/developer-dao/pull/117 is merged.

**Comment by kavimaluskam** [comment]
Updated the PR w.r.t. https://github.com/Developer-DAO/developer-dao/pull/117

**Review by narbs91 — APPROVED** [review]
LGTM, thanks for the contribution here @kavimaluskam !

**Pull request merged**
