### PR TITLE
Add new version of the website

### LINKED ISSUE #205: Components Listing
- [x] #206
- [x] #207
- [x] #208
- [x] #209
- [x] #210

All the components should be developed keeping in mind the responsiveness and the consistency of the code. 

I've added the different [variants](https://github.com/Developer-DAO/developerdao.com/blob/be23acedf3daa10accf53b9fb3a70ddc5fad2eb1/src/theme.ts#L26) for `Text` and `Heading` elements of the Chakra UI as per the fonts and size of the text in the Figma design. Use these variants, while developing the components.

Figma link: https://www.figma.com/file/W2MGe36aUKYzaE3EaWQIm5/Developer-DAO-website-2022?node-id=2%3A596
For the icons in the Footer, use [react-icons](https://react-icons.github.io/react-icons/)

### PR DESCRIPTION
**Pull request by Nazeeh21**
### What does it do?
This PR contains the new version of the D_D website

### Relevant screenshots/gifs
https://user-images.githubusercontent.com/56908732/163688372-e97dfd3d-3964-44d1-8768-e10a1d0721b9.mov

### Closes #205

### CODE REVIEW

**Comment by mhmulford0** [comment]
@kempsterrrr let's deploy a preview please so i can make sure works on remote. I resolved all the merge conflicts and did some other chore type things.

**Comment by kempsterrrr** [comment]
nice work @mhmulford0 - I think this is looking good cc @Nazeeh21 @mohamedsadiq thoughts?

**Comment by kempsterrrr** [comment]
Noting a few things to remember:

1. Looks like someone has implemented Plausible Analytics, who has access to this?
2. Currently handling all SEO globally in the app component, should probably create a reusable SEO component as we expand beyond a single page. 
3. The og:image below is pretty boring, wonder if @mohamedsadiq fancies creating an updated one?

Screenshot 2022-07-23 at 11 43 44

**Comment by mhmulford0** [comment]
With regards to Plausible Analytics: There are some considerations to be made about using this package. That code is licensed under AGPL, a strong copy-left license. In short, that means code that uses PA must also be released under the [AGPL](https://github.com/plausible/analytics/blob/master/LICENSE.md). Presently the repo has a MIT license meaning that we are not in "compliance" or whatever the term for that would be. 

I don't have any issues with AGPL but i am also not sure if it is the best fit?

**Comment by Nazeeh21** [comment]
> nice work @mhmulford0 - I think this is looking good cc @Nazeeh21 @mohamedsadiq thoughts?

Tysm @mhmulford0, Its very nice, great job

**Comment by kempsterrrr** [comment]
Let's remove plausbible and then deploy this asap

**Pull request merged**
